### ISSUE TITLE
D3Dshot on linux platform

### ISSUE THREAD

**Issue by pythonlessons** [SerpentAI/D3DShot#15]
As I understand this library is only for Windows,

Will this be made for linux any time soon? 

Receiving following error:
>     import d3dshot
>   File "/usr/local/lib/python3.7/dist-packages/d3dshot/__init__.py", line 4, in <module>
>     from d3dshot.d3dshot import D3DShot
>   File "/usr/local/lib/python3.7/dist-packages/d3dshot/d3dshot.py", line 8, in <module>
>     from d3dshot.display import Display
>   File "/usr/local/lib/python3.7/dist-packages/d3dshot/display.py", line 1, in <module>
>     import d3dshot.dll.dxgi
>   File "/usr/local/lib/python3.7/dist-packages/d3dshot/dll/dxgi.py", line 2, in <module>
>     import ctypes.wintypes as wintypes
>   File "/usr/lib/python3.7/ctypes/wintypes.py", line 20, in <module>
>     class VARIANT_BOOL(ctypes._SimpleCData):
> ValueError: _type_ 'v' not supported

**Comment by RabbitHols** [comment]
It's use Desktop Duplication Api, that is a Direct X api so it will work only on windows. If you want something similar try something with OpenGL or Vulkan.

**Comment by nbrochu** [comment]
Yeah I love to support as many platforms as possible in my projects but D3DShot purely leverages Windows APIs so there is not much that can be done there. If you want easy screen capture in Linux, you could always use [mss](https://github.com/BoboTiG/python-mss). It's not as fast but very good otherwise. It's what I use in Serpent.AI
