### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by simdimdim** [SerpentAI/D3DShot#2]
Very nice!

Tho I'd like to ask something directly, since you're more familiar with the code.
If I wanted to not receive duplicate frames when there's no change, how should I go about altering the functions so it'd return just the new data and a value of number of how many frames have been the same so far ? Thanks in advance :)

**Comment by nbrochu** [comment]
The Windows Desktop Duplication API itself doesn't return duplicate frames. I added that functionality to have a consistent buffer where frames are tied to time. Thankfully, it should be easy to modify for your use case since it's handled in Python and not the DLL sections.

Check this out: https://github.com/SerpentAI/D3DShot/blob/master/d3dshot/d3dshot.py#L279

Just adapt the else clause to your needs.

**Comment by simdimdim** [comment]
Oh, the timing is even in the same call. Thanks o/. Cheers.
